### ISSUE TITLE
Lazy initialization

### ISSUE THREAD

**Issue by dalevink** [pelotom/use-methods#10]
I wonder if you'd consider adding lazy initialization? 

It could mimic the useReducer API, eg:

`const [state, dispatch] = useReducer(reducer, initialArg, init);`
https://reactjs.org/docs/hooks-reference.html#usereducer

... potentially without breaking changes (as far as I can tell).

I'd make a new pull request myself but your TS typing is beyond my current level!

**Comment by pelotom** [comment]
Done 👍

**Comment by dalevink** [comment]
Nice one, thanks a lot! Great little library too BTW.
