### ISSUE TITLE
Using Immer Patches Functionality

### ISSUE THREAD

**Issue by dfbaskin** [pelotom/use-methods#12]
The Patches functionality of Immer is useful for things like building JSON patches, undo/redo, etc.
https://github.com/immerjs/immer#patches

Does it make sense to expose this functionality in `useMethods` somehow?  Or is this just complicating things too much?

**Comment by pelotom** [comment]
It's an interesting idea, did you have an API in mind? I could imagine a third element in the result tuple which exposes this functionality, e.g.

```js
const [state, callbacks, { undo, redo }] = useMethods(methods, initialState);
```

**Comment by dfbaskin** [comment]
Take the typical TODO list example. The state is the list of TODOs and we want to persist this state using JSON patches to a web api (rather than sending the entire list of TODOs).  If we use Immer's api:

```javascript
    // The third argument to produce is a callback to which the patches will be fed
    (patches, inversePatches) => {
        changes.push(...patches)
        inverseChanges.push(...inversePatches)
    }
```

then the patch handler could just be passed in as the 3rd argument to the `useMethods` function:

```javascript
const [state, callbacks] = useMethods(methods, initialState, (patches) => {
    // ... convert to JSON patch
    // ... perform async operation to send JSON patch to web api
});
```

That seems to line up with how you might handle other types of callbacks.

**Comment by pelotom** [comment]
There's already a third optional parameter to `useMethods` which mirrors [that of `useReducer`](https://reactjs.org/docs/hooks-reference.html#lazy-initialization). We could add a 4th parameter, but that then requires you to provide the 3rd, which is in most cases superfluous, and also 4 parameters is starting to be a lot.

What about returning the `patches` and `inversePatches` in the third tuple element? Then you could use `useEffect` to do things with them:

```ts
const [
  state,
  callbacks,
  { patches, inversePatches },
] = useMethods(methods, initialState);

const changes = useRef([]);
const inverseChanges = useRef([]);
useEffect(() => {
  changes.current.push(...patches);
  inverseChanges.current.push(...inversePatches);
}, [patches, inversePatches]);
```

**Comment by dfbaskin** [comment]
Seems like you might lose patches if more than one of the `callbacks` were executed.

I'll play around this weekend with it and put together a PR.

**Comment by pelotom** [comment]
Should be able to coalesce any number of patches that occur between updates, no?

**Comment by dfbaskin** [comment]
I think that should be opt-in behavior, though.  If the library has to coalesce patches, then maybe we need another API altogether, like `useMethodsWithPatches`, something like that.

**Comment by dfbaskin** [comment]
I went with attaching the patches callback to the `methods` function.  What do you think?
