### ISSUE TITLE
Sources are not included in published package, even though the source maps point to them

### ISSUE THREAD

**Issue by JReinhold** [pelotom/use-methods#15]
Hi! First of all, thanks for this awesome package!

## The problem

The published package only includes the `dist` folder, however the generated source map at `dist/index.js.map` points to sources at `../src/index.ts`.

This means that the source maps are effectively unusable, as they point to a file that is not available.
It also results in a warning when using this package with Parcel. Every time the application is built, Parcels shows the following warning:
```
⚠️ Could not load source file "../src/index.ts" in source map of "../node_modules/use-methods/dist/index.js".
```

## Possible solutions

1. Inline sources directly within the source map using the [`--inlineSources` flag](https://www.typescriptlang.org/docs/handbook/compiler-options.html) when compiling with `tsc`
2. Publish sources as well, by changing the `files` property in `package.json` to:
```
"files": [
    "dist",
    "src"
  ]
```
3. Disable source map generation completely, by setting the `sourceMap` property to `false` in `tsconfig.json`.

I don't think there's any practical difference between option 1 and 2, I assume it's just a matter of preference. Option 3 favours a leaner package at the expense of not having source available when developing.
I would strongly hope that you choose option 1 or 2 over 3. 🙂

**Comment by pelotom** [comment]
Thanks for the detailed writeup; I went with option 2, released in v0.5.1 🚀
