### ISSUE TITLE
Alternative syntax using `this`?

### ISSUE THREAD

**Issue by pelotom** [pelotom/use-methods#2]
An alternate, more "method"-y API would be to use `this` as the state variable, which would mean you could provide a simple record instead of a function of state:

```js
const initialState = { count: 0 };

const methods = {
  reset() {
    return initialState;
  },
  increment() {
    this.count++;
  },
  decrement() {
    this.count--;
  },
};
```

Another advantage is that VSCode gives `this` special emphasis and color, so it's easy to tell at a glance where state access and "mutation" is happening.

Downsides of this approach:
- Can't use arrow functions to define methods
- Can't decide to use a shorter name for the state variable, e.g. `s`
- Can't compute variables from state that will be in scope for all methods, e.g.:
  ```js
  const methods = state => {
    const { x, y, z } = state;
    return {
      // ... method definitions
    }
  };
  ```

I'm curious if others have any opinions about this.

**Comment by IniZio** [comment]
Or maybe something like 

```js
const methods = {
  reset: () => () => initalState,
  increment: state => count => (state += count)
}
```

?

**Comment by pelotom** [comment]
> Or maybe something like
> 
> ```js
> const methods = {
>   reset: () => () => initalState,
>   increment: state => count => (state += count)
> }
> ```
> 
> ?

The nice thing about the current API is that you only have to declare a state parameter once, for all your methods. Using an implicit `this` would make it so you don't have to even do that. But it sounds like you're suggesting each method would have to declare its own state parameter, which seems like a step backwards...

**Comment by EmilTholin** [comment]
With this approach, will `this` be bound to the state? The current approach is nice in that you don't have to worry about how you invoke one of the methods.

```javascript
<button onClick={reset}>Reset</button>
```

I personally think it would not be as nice if this was required with the `this` approach.

```javascript
<button onClick={() => reset()}>Reset</button>
```

**Comment by pelotom** [comment]
Yeah, `this` would always be bound, because we wouldn’t be using classes, just generating a bunch of functions which come pre-bound to their context.

**Comment by TedDriggs** [comment]
I like it as-is (without `this`), partially because we use a lint that disallows `this` outside class bodies, and partially because `this` is a piece of JS magic that always seems suspicious.

**Comment by pelotom** [comment]
We could do this without disrupting the existing API by just providing an optional helper that would work like this:

```ts
const methods = createMethods<State>({
  increment() {
    this.count++;
  },
  decrement() {
    this.count--;
  },
});

// equivalent to:

const methods = (state: State) => ({
  increment() {
    state.count++;
  },
  decrement() {
    state.count--;
  },
});
```

The question is, would anybody use it?

**Comment by pelotom** [comment]
It feels superfluous, gonna close.
