### ISSUE TITLE
Should state be kept separate from callbacks in the returned result?

### ISSUE THREAD

**Issue by pelotom** [pelotom/use-methods#4]
Currently we return an object from `useStateMethods` which is a mixture of state and callbacks:

```js
const initial = { count: 0 };

const methods = state => ({
  increment() {
    state.count++;
  },
  decrement() {
    state.count--;
  },
});

// ...

const { count, increment, decrement } = useMethods(initial, methods);
```

but maybe they should be kept separate, a la `useState` and `useReducer`:

```js
const [{ count }, { increment, decrement }] = useMethods(initial, methods);
```

One advantage of this would be the option to use primitives instead of objects for state. For example in this case we could use a simple number for the state:

```js
const initial = 0;

const methods = count => ({
  increment: () => count + 1,
  decrement: () => count - 1,
});

// ...

const [count, { increment, decrement }] = useMethods(initial, methods);
```

**Comment by sidoshi** [comment]
I think keeping state and methods separate is better. It would also help avoid conflicts between state key and methods.

**Comment by pelotom** [comment]
Yeah, I think I'm leaning that way too.

**Comment by Noitidart** [comment]
Awesome! Is your 2nd example how things work now? So I can do:

```
const initial = 0;

const methods = count => ({
  increment: () => count + 1,
  decrement: () => count - 1,
});

// ...

const [count, { increment, decrement }] = useMethods(initial, methods);
```?

**Comment by pelotom** [comment]
@Noitidart yes, except that I've also reversed the argument order (#3) to be consistent with that of `useReducer`, so:

```js
const [count, { increment, decrement }] = useMethods(methods, initial);
```

**Comment by Noitidart** [comment]
Thank you! Super awesome!
