### ISSUE TITLE
Controlled forms; multiple event calls

### ISSUE THREAD

**Issue by ja0nz** [pelotom/use-methods#6]
I faced some issues when using controlled forms. It seems like the onChange method is called multiple times. Here is the issue, enter something: 

https://codesandbox.io/s/2zoqzx13wn?expanddevtools=1&fontsize=14

Example taken from the official docs https://reactjs.org/docs/forms.html

**Comment by pelotom** [comment]
That's odd, I'm not sure what's going on there. But it seems to afflict the `useReducer` version too? https://codesandbox.io/s/rynqx6k4qo

**Comment by pelotom** [comment]
It looks like this is due to `useReducer` sometimes being called asynchronously. See [this comment](https://github.com/facebook/react/issues/13990#issuecomment-433629390) for explanation and workarounds.

**Comment by ja0nz** [comment]
Funny behavior. Its working with the workaround though: 
```
const methods = state => ({
  handleChange(value) {
    state.value = value;
  }
})
...
<input type="text" value={value} onChange={event => handleChange(event.target.value)} />
```
