### ISSUE TITLE
Should method be called twice?

### ISSUE THREAD

**Issue by jon64digital** [pelotom/use-methods#7]
Just trying out useMethod for the first time and I noticed something. Here is my code:

```
import useMethods from 'use-methods'


// Initial State
const initialState = { 
    token: ''
};


// Methods
const methods = state => ({

    setToken(newToken) {
        console.log("useMethod setting token", newToken)
        state.token = newToken
    }

})


// Hook
export default function useAuthContextValue() {

    const [
        {token}, 
        {setToken}
    ] = useMethods(methods, initialState);

    return {
        token,
        setToken
    }

}
```

My console log is being logged twice each time I call setToken. I checked that I wasn't calling it twice from my consuming component by putting a console.log directly before the line that calls setToken and that log only happens once.

Is this expected behaviour?

**Comment by pelotom** [comment]
I do see that it's being called twice on the first invocation, but only once on subsequent invocations... is that what you're seeing?

**Comment by pelotom** [comment]
Looks like this is an issue with `useImmerReducer`: https://github.com/mweststrate/use-immer/issues/11

**Comment by pelotom** [comment]
Opened a PR there to fix it: https://github.com/mweststrate/use-immer/pull/12

**Comment by pelotom** [comment]
Switched to use `immer` directly intead of `use-immer` and fixed the bug internally.

**Comment by jon64digital** [comment]
I hadn't checked what happens on subsequent renders but great to hear you've tracked the problem down.
