### ISSUE TITLE
make it clear that the whole "callbacks" object is memoized

### ISSUE THREAD

**Issue by pocesar** [pelotom/use-methods#8]
I was unnecessarily passing individual methods to `useEffect` / `useCallback` instead of passing the whole `callbacks` from `[state, callbacks]`. I noticed it's memoized from looking the code, would be nice to make it clear that the whole object is stable

so doing:

```ts
const [state, callbacks] = useMethods(methods, initialState)

const = myCallback = useCallback(() => {
  callbacks.something()
}, [callbacks])
```

works

**Comment by pelotom** [comment]
Sounds good, would you like to open a PR to add something about that to the README?
